import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Client } from "../../prismic/prismic";

import { RichText } from "prismic-reactjs";
import { htmlSerializer } from "../../prismic/htmlSerializer";
import Container from "../../components/Container";
import Link from "next/link";

// const linkResolver = (doc: any) => {
//   // Pretty URLs for known types
//   if (doc.type === "blog") return "/post/" + doc.uid;
//   if (doc.type === "page") return "/" + doc.uid;
//   // Fallback for other types, in case new custom types get created
//   return "/doc/" + doc.id;
// };

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: true,
  };
}

export async function getStaticProps(context: any) {
  const document = await Client.getByUID("blog-post", context.params.slug, {});
  return {
    props: {
      document,
    },
  };
}

const Home: NextPage = ({ document }: any) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="p-4 shadow-md mb-6">
        <Link href="/blog" passHref>
          <svg
            className="mx-auto cursor-pointer"
            width="66"
            height="44"
            viewBox="0 0 66 44"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M19.2688 21.7112L8.92894 0.0163269H0L14.8037 31.0768L19.2688 21.7112Z"
              fill="#231F20"
            />
            <path
              d="M39.1576 12.9232L34.6963 22.2888C34.695 22.29 34.695 22.2913 34.6963 22.2938L45.0399 44L49.5013 34.6344C49.5025 34.6332 49.5025 34.6319 49.5013 34.6294L39.1576 12.9232Z"
              fill="#231F20"
            />
            <path
              d="M57.0708 0.0163269L46.7334 21.7125L51.196 31.0768L65.9997 0.0163269H57.0708Z"
              fill="#231F20"
            />
            <path
              d="M33.0017 0L16.4971 34.6305L20.9622 43.9974L37.4631 9.36937C37.4643 9.36811 37.4643 9.3656 37.4631 9.36434L33.0017 0Z"
              fill="#231F20"
            />
          </svg>
        </Link>
      </header>
      <main>
        <Container>
          <div className="prose">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={document?.data.image.url}
              alt={document?.data.image.alt}
              className="rounded-md"
            />
            <h1>{document?.data.title[0].text}</h1>

            {document && (
              <RichText
                render={document.data.body[0].primary.text}
                htmlSerializer={htmlSerializer}
              />
            )}
          </div>
        </Container>
      </main>
    </div>
  );
};

export default Home;
