import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Prismic from "@prismicio/client";
import { Client } from "../../prismic/prismic";
import Link from "next/link";
import Container from "../../components/Container";

export async function getStaticProps() {
  const { results } = await Client.query(
    Prismic.Predicates.at("document.type", "blog-post")
  );

  return {
    props: {
      blogPosts: results,
    },
  };
}

const Home: NextPage = ({ blogPosts }: any) => {
  return (
    <div>
      <Head>
        <title>Blog page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="p-4 shadow-md mb-6">
        <h1 className="text-center font-bold text-2xl">Welhome Blog</h1>
      </header>
      <main>
        <Container>
          <div className="grid grid-cols-3 gap-4">
            {blogPosts.map((post: any) => {
              return (
                <Link href={`/blog/${post.slugs[0]}`} key={post.id}>
                  <a>
                    <div className="rounded-lg relative overflow-hidden">
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img
                        src={post.data.image.url}
                        alt={post.data.image.alt}
                        width="100%"
                      />
                      <div className="absolute inset-0 bg-gradient-to-b from-transparent to-black/50" />
                      <h2 className="absolute bottom-0 w-full p-3 text-white font-bold text-md">
                        {post.data.title[0].text}
                      </h2>
                    </div>
                  </a>
                </Link>
              );
            })}
          </div>
        </Container>
      </main>
    </div>
  );
};

export default Home;
