import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Link from "next/link";
import Container from "../components/Container";

const Home: NextPage = ({ blogPosts }: any) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header className="p-4 shadow-md mb-6">
          <h1 className="text-center font-bold text-2xl">Welhome Blog</h1>
        </header>
        <Container>
          <Link href="/blog">
            <a>Go to blog page</a>
          </Link>
        </Container>
      </main>
    </div>
  );
};

export default Home;
