import type { NextPage } from "next";
import Head from "next/head";
import * as prismic from "@prismicio/client";

export async function getStaticProps() {
  const endpoint = prismic.getEndpoint("blog-properties-demo");
  const client = prismic.createClient(endpoint);
  const blogPosts = await client.getAllByType("blog-post");

  return {
    props: {
      blogPosts,
    },
  };
}

const Home: NextPage = ({ blogPosts }: any) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Blog demo</h1>
        {blogPosts.map((post: any) => {
          return <h2 key={post.id}>{post.data.title[0].text}</h2>;
        })}
      </main>
    </div>
  );
};

export default Home;
